[2024-09-22 23:55:26,640] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-22 23:55:26,640] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-22 23:55:26,642] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-22 23:55:28,286] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-22 23:55:28,288] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-22 23:57:58,154] INFO _log() L96   127.0.0.1 - - [22/Sep/2024 23:57:58] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-22 23:57:58,242] INFO _log() L96   127.0.0.1 - - [22/Sep/2024 23:57:58] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-22 23:57:58,251] INFO _log() L96   127.0.0.1 - - [22/Sep/2024 23:57:58] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-22 23:57:58,252] INFO _log() L96   127.0.0.1 - - [22/Sep/2024 23:57:58] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-22 23:57:58,408] INFO _log() L96   127.0.0.1 - - [22/Sep/2024 23:57:58] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-22 23:57:58,620] INFO _log() L96   127.0.0.1 - - [22/Sep/2024 23:57:58] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-22 23:58:15,442] WARNING add_paciente() L87   Erro ao adicionar paciente 'João': Não foi possível salvar novo usuário :/ - Detalhes: 'numpy.ndarray' object has no attribute 'predict' - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\predicao_doencas_cardiacas\app.py L87  
[2024-09-22 23:58:15,443] INFO _log() L96   127.0.0.1 - - [22/Sep/2024 23:58:15] "[31m[1mPOST /paciente HTTP/1.1[0m" 400 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:21:57,616] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:21:57,617] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:21:57,618] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:21:59,908] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:21:59,910] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:22:14,524] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 00:22:14] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:22:14,805] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 00:22:14] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:22:14,818] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 00:22:14] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:22:14,819] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 00:22:14] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:22:14,976] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 00:22:14] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:22:15,088] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 00:22:15] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:22:32,037] WARNING add_paciente() L93   Erro ao adicionar paciente 'João': Não foi possível salvar novo usuário :/ - Detalhes: 'numpy.ndarray' object has no attribute 'predict' - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\predicao_doencas_cardiacas\app.py L93  
[2024-09-23 00:22:32,037] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 00:22:32] "[31m[1mPOST /paciente HTTP/1.1[0m" 400 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:25:57,382] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\OneDrive\\Área de Trabalho\\predicao_doencas_cardiacas\\model\\paciente.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:25:57,630] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:25:59,507] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:25:59,509] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:26:01,531] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\OneDrive\\Área de Trabalho\\predicao_doencas_cardiacas\\model\\paciente.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:26:01,776] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:26:03,643] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:26:03,645] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:27:53,271] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\OneDrive\\Área de Trabalho\\predicao_doencas_cardiacas\\model\\avaliador.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:27:53,547] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:27:56,542] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 00:27:56,544] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 15:17:44,651] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 15:17:44,652] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 15:17:44,655] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 15:17:46,305] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 15:17:46,307] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
