[2024-09-23 16:45:00,654] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 16:45:00,656] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 16:45:00,659] INFO _log() L96    * Restarting with stat - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 16:45:02,817] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 16:45:02,820] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 16:45:30,271] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 16:45:30] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 16:45:30,395] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 16:45:30] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 16:45:30,445] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 16:45:30] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 16:45:30,454] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 16:45:30] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 16:45:30,600] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 16:45:30] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 16:45:30,705] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 16:45:30] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 16:45:34,905] WARNING add_paciente() L97   Erro ao adicionar paciente 'João': Paciente já existente na base :/ - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\MVP\app_classifica_problema_cardiaco_api\app.py L97  
[2024-09-23 16:45:34,906] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 16:45:34] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:36:26,363] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:36:26,364] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:36:26,371] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:36:28,132] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:36:28,135] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:38:01,185] INFO _log() L96    * Detected change in 'C:\\Users\\juan_\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\sklearn\\base.py', reloading - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:38:01,205] WARNING add_paciente() L97   Erro ao adicionar paciente 'João': Paciente já existente na base :/ - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\MVP\app_classifica_problema_cardiaco_api\app.py L97  
[2024-09-23 17:38:01,210] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 17:38:01] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:38:01,705] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:38:03,489] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:38:03,491] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:38:17,974] WARNING add_paciente() L97   Erro ao adicionar paciente 'João': Paciente já existente na base :/ - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\MVP\app_classifica_problema_cardiaco_api\app.py L97  
[2024-09-23 17:38:17,976] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 17:38:17] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:40:10,201] WARNING add_paciente() L97   Erro ao adicionar paciente 'João': Paciente já existente na base :/ - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\MVP\app_classifica_problema_cardiaco_api\app.py L97  
[2024-09-23 17:40:10,203] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 17:40:10] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:40:50,476] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:40:50,477] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:40:50,489] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:40:52,701] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:40:52,703] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:42:38,212] WARNING add_paciente() L97   Erro ao adicionar paciente 'João': Paciente já existente na base :/ - call_trace=C:\Users\juan_\OneDrive\Área de Trabalho\MVP\app_classifica_problema_cardiaco_api\app.py L97  
[2024-09-23 17:42:38,214] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 17:42:38] "[31m[1mPOST /paciente HTTP/1.1[0m" 409 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:45:21,428] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:45:21,428] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:45:21,441] INFO _log() L96    * Restarting with watchdog (windowsapi) - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:45:23,379] WARNING _log() L96    * Debugger is active! - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:45:23,381] INFO _log() L96    * Debugger PIN: 132-689-196 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:45:39,004] INFO _log() L96   127.0.0.1 - - [23/Sep/2024 17:45:39] "POST /paciente HTTP/1.1" 200 - - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:49:53,314] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-09-23 17:49:53,315] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\juan_\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
